################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "[KFCDAO](https://kfcdao.com/)"



################################### French language #####################################
[zh]
languageName = "简体中文"
languageCode = "zh-cn"
contentDir = "content/chinese-simplify"
weight = 2
# copyright
copyright = "[KFCDAO](https://kfcdao.com/)"