#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "60px"
# if logo_webp set false, it will not generate WEBP version of logo
logo_webp = true # default is true
# logo text will only show when logo is missing.
logo_text = "KFCDAO"
# image gallery shortcode
image_gallery = true

# footer information
footer_info = "Crazy Thursday"

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# career form action
career_form_action = "#" # career form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# Main Sections
mainSections= ["blog"]

[variables]
font_size = "16px"
white = "#E41E28"
black = "#FFFFFF"
light = "#cfcfcf"
primary_color = "#000000"
border_color = "#686868"
# white = "#ffffff"
# black = "#000000"
# primary_color = "#E41E28"

# plugins js
[[plugins.js]]
link = "plugins/aos/aos.js"

[[plugins.js]]
link = "plugins/jquery/jquery.min.js"

[[plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[plugins.js]]
link = "plugins/gallery/glightbox.js"

[[plugins.js]]
link = "plugins/swiper/swiper-bundle.min.js"

[[plugins.js]]
link = "plugins/rellax/rellax.min.js"

[[plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"

# plugins css
[[plugins.css]]
link = "plugins/aos/aos.css"

[[plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"

[[plugins.css]]
link = "plugins/swiper/swiper-bundle.min.css"

# contact information
[contact_info]
# address = "2118 Thornridge Cir. Syracuse, Connecticut 35624"
# phone = ["+704-555-0127", "+205-857-2321", "+002-569-6969"]
# email = ["info@andromeda.io", "smith@anderson.io", "john@anderson.io"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Comming Soon"
link = "#"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["KFCDAO", "KFC4", "V50", "KFC4V50"]
description = "KFCDAO"
author = "KFCDAO"
image = "images/og-image.jpg" # this image will be used as fallback if a page has no image of its own

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
facebook = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = false
title = "Helping teams in the world with focus"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
button = "Download The Theme"
button_link = "/"

############################# social site ########################
# [[social]]
# title = "Andromeda"
# icon = "lab la-facebook-f" # https://icons8.com/line-awesome
# link = "#!"

[[social]]
title = "KFCDAO Twitter"
icon = "lab la-twitter" # https://icons8.com/line-awesome
link = "https://twitter.com/KFCDAOcom"

# [[social]]
# title = "AndromedaIn"
# icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
# link = "#!"

# [[social]]
# title = "AndromedaPin"
# icon = "lab la-pinterest" # https://icons8.com/line-awesome
# link = "#!"